name: Change Management Trigger

on:
  repository_dispatch:
    types: [change_update]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Execute Task
      run: echo "Triggered by ServiceNow change request."
