name: ServiceNow Gate Check

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-change-state:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Change Request State
        run: |
          echo "This is where you would validate the change request state."
